### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by monsieurbecker** [ertaiNL/multiFormatSave#4]
The line "File Format" (head line of the box) has been translated wrongly as "Dateien Formate". The correct translation is "Dateiformate".

**Comment by ertaiNL** [comment]
Thank you for your help. I have solved the issue and it will be shipped in the next version.

**Comment by monsieurbecker** [comment]
I have just found the file DialogStrings_de_DE.properties, there are two more string that need to be changed:
InputFormatError=Mindestens ein Dateiformat muss ausgew\u00e4hlt werden
SaveError=Ein Fehler ist w\u00e4rend des Speichervorgangs der Datei aufgetreten, versichern Sie sich, dass die ausgesuchten Dateien geschlossen sind.

**Comment by ertaiNL** [comment]
Thank you for your help. I have updated the translations.

Please next time create a new issue, or reopen the issue, if you have more items as updates on closed issues can be missed.
