### ISSUE TITLE
MultiFormatSave bug

### ISSUE THREAD

**Issue by ChiefHart** [ertaiNL/multiFormatSave#5]
I use Ubuntu 16.04.5 LTS and LibreOffice 6.1.3.2 and MultiFormatSave does NOT work with it  I get a Basic run problem notice.
There is a problem with the code, I think it is line 440, but am not sure as I am not a code writer. That is the one that gets highlighted with the bug.

**Comment by ertaiNL** [comment]
Thank you for posting this bug. I tried it with LibreOffice 6.1.3.2 (although I have Ubuntu 18.04.1 LTS). But I can't reproduce it easily. Can you give me more information?

Can you answer the following questions for me so I can pinpoint more what is happening?
- What version of MultiFormatSave are you running? If you go to the menu 'Tools' and then select 'Extension Manager' you should be able to see it there.
- What program are you using when saving (writer/calc/impress/draw)? Or does it happen with all programs?
- What formats are you trying to save in? (or is it with all?)

Many thanks!

**Comment by ChiefHart** [comment]
![SMultisave](https://user-images.githubusercontent.com/45080732/59474234-0e2f9400-8e14-11e9-864f-ab658867e62a.png)
This is the message I get.  I have had this problem with 16.04LTS and now a new computer with POP!_OS (based on Ubuntu 18.04LTS) and LibreOffice 6.2.4.2.

**Comment by ChiefHart** [comment]
I can send the app code if needed.

**Comment by ChiefHart** [comment]
I finally got it to work.  I had Multisave and Multiformatsave extensions and I think the Multiformatsave  was adversly affected by the older Multisave.  I disabled Multisave and tried Multiformatsave again and it worked liked it used to do on my older computer. So not a bug, but two similar apps that somehow got tangle when one was activated..

**Comment by ertaiNL** [comment]
Thank you for letting me know.
