### ISSUE TITLE
Add .docx support

### ISSUE THREAD

**Issue by SouthernWolf95** [ertaiNL/multiFormatSave#6]
I was wondering if it would be possible to add support for saving to .docx files as that would greatly help with my ability to produce files in both formats! Is this possible? Normall what I do now is save my main file in ODF, then "Save a copy..." as a .docx file of the same name. Is this addition possible?

**Comment by ertaiNL** [comment]
Thanks for the request, but I dropped support for OpenOffice.org.
In LibreOffice the option is available.
