### ISSUE TITLE
multiFormatSave is broken

### ISSUE THREAD

**Issue by ChiefHart** [ertaiNL/multiFormatSave#8]
This will not work with LO 6.3.1.2. It worked before the last LO upgrade but does not work now.
![image](https://user-images.githubusercontent.com/45080732/66089574-f5c3c080-e54d-11e9-81cf-4b8e48d10521.png)
I hope the image is viewable.  It states the file does not exist.  So how does one install a file that does not exist?

**Comment by ertaiNL** [comment]
I have tested the plugin with LO 6.3.1.2 on Ubuntu 18.04.3 and there the plugin works. I also tried removing and reinstalling it. What OS are you using (and what version).

You can also move your profile /home/jlh68/.config/libreoffce to a different directory and then try with a new profile. If that works then there is a problem in your profile. (and you can move it back to keep your settings.) Please let me know if it works then.

I will try more soon to see if I can reproduce it.

**Comment by ChiefHart** [comment]
I still have this problem with the download of your application.  MultiSave is the only extension that saves or doe not save in my LibreOffice Extensions.  I have tried other extensions and the will install correctly.  I have included the screenshot of the message I still get when installing MultiSave
![image](https://user-images.githubusercontent.com/45080732/71312804-7384c300-23fd-11ea-9f81-e93c1f90b229.png)
![MultiSave](https://user-images.githubusercontent.com/45080732/71312811-9616dc00-23fd-11ea-97af-3ac4a2371e53.png)

**Comment by ChiefHart** [comment]
MultiSave is in my download folder, but I get the message that it does not exist.  So where is it hiding?

**Comment by ertaiNL** [comment]
Hi,

I can't find anything wrong in the code or with the version of libreOffice that you are running. Why it can't find it I also don't know.

In this page https://wiki.documentfoundation.org/UserProfile you can find more info about the profile. I think there is something wrong with the profile. But I don't really know a lot about that.

Maybe best to ask the LibreOffice support if they know about this kind of problem.
I suggest creating a question at https://ask.libreoffice.org. If you do you can copy the URL here and I will also keep an eye on that to see if I can provide info where I can.

**Comment by ertaiNL** [comment]
#9 has been solved with an update of LibreOffice. The issue seems simular to me. Can you check?

**Comment by ertaiNL** [comment]
closed due to no reaction

**Comment by ertaiNL** [comment]
Reply of @ChiefHart 
> Multi save has been broken for me over three computers and three operating systems. It did not work with Ubuntu 18.04LTS, or Ubuntu 20.04LTS, and it does not work with POP!_OS either.
> I keep getting a message when using LO Extension Manager that multi-save does not exist. I would upload an image of it if it was allowed.
> ![image](https://user-images.githubusercontent.com/45080732/89834927-bd0f5300-db31-11ea-9652-b3cbad3c0ec1.png)

**Comment by ChiefHart** [comment]
Well miracles exist.  When I updated LibreOffice to 7.0.1 and tried to add the MultiFormatSave extension it added and worked. I wonder if the LO versions from Ubuntu had a different path than  a non Ubuntu version of LO?  It is strange as I had trouble with 3 versions of Ubuntu, and on several computers, and now Ihave it on two computes and it is working like it did 3 or 4 years ago. I now have MFS working on a System76 DarterPro laptop with POP!_OS, and on an Acer Netbook with POP!_OS, both have LibreOffice 7 installed.
